#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

cd /

mkdir -p /dev/block
mkdir -p /sdcard

mknod -m 0644 /dev/block/mmcblk0 b 179 0
mknod -m 0644 /dev/block/mmcblk0p1 b 179 1

busybox mount -t vfat /dev/block/mmcblk0p1 /sdcard
busybox date >>boot.txt
exec >>/sdcard/boot.txt 2>&1 

mkdir -p /mnt/.lfs
mkdir -p /proc
mkdir -p /sys

mknod -m 0644 /dev/block/bml6 b 137 6
mknod -m 0644 /dev/block/stl6 b 138 6
mknod -m 0644 /dev/mem c 1 1

insmod /lib/modules/fsr.ko
insmod /lib/modules/fsr_stl.ko


mount -t proc proc /proc
mount -t sysfs sysfs /sys

insmod /lib/modules/j4fs.ko
mount j4fs /dev/block/stl6 /mnt/.lfs
insmod /lib/modules/param.ko

REC_BOOT_ADDR="0x57fff800"
REC_BOOT_MAGIC="0x5EC0B007" # Must be in caps.

devmem "$REC_BOOT_ADDR" 32 "$REC_BOOT_MAGIC"

umount /sdcard
rm -rf /sdcard

umount /sys
umount /proc

rm -rf /stage1 
rm -rf /dev/*
busybox date >>/sdcard/boot.txt
reboot

